Repository elastisys/compliantkubernetes-apps, pull requests merged in 2021-04, with the labels that each got.

#375 docs: Update release document
  release/README.md
Labels: not planned

#383 apps sc: elasticsearch slm script deletes indices in bulk
  WIP-CHANGELOG.md
  helmfile/charts/elasticsearch-slm/scripts/slm-retention.bash
Labels: elasticsearch, not planned

#399 apps sc: update image for influx restore to match influx
  manifests/restore/restore-influx.yaml
Labels: not planned

#404 apps sc: Fixed typo in auth log
  helmfile/values/opendistro-es.yaml.gotmpl
Labels: bug, not planned

#425 bin: Fix check for bash array in team.bash
  WIP-CHANGELOG.md
  bin/team.bash
Labels: bug, not planned, quick issue
