Repository elastisys/compliantkubernetes-apps, pull requests merged in 2021-06, with the labels that each got.

#471 Added migration script for the CRDs
  migration/v0.15.x-v0.16.x/migrate-crd.sh
  migration/v0.15.x-v0.16.x/upgrade-apps.md
Labels: QA

#484 config: update default cluster DNS IP to match kubespray defaults
  WIP-CHANGELOG.md
  config/config/sc-config.yaml
  config/config/wc-config.yaml
  pipeline/config/exoscale/sc-config.yaml
  pipeline/config/exoscale/wc-config.yaml
Labels: not planned

#487 pipeline: add back missing files
  pipeline/apply-sc.bash
  pipeline/apply-wc.bash
  pipeline/list-releases.bash
Labels: not planned, pipeline

#468 [1] Added script to make it easier to update secrets
  README.md
  WIP-CHANGELOG.md
  scripts/generate-secrets.sh
Labels: not planned

#501 apps sc & wc: fix cluster prometheus tests
  WIP-CHANGELOG.md
  pipeline/test/services/service-cluster/testPrometheusTargets.sh
  pipeline/test/services/workload-cluster/testPrometheusTargets.sh
Labels: bug, not planned

#499 Fixed issue where curator would fail to start with postgres enabled
  WIP-CHANGELOG.md
  helmfile/elastisys/opendistro-es/templates/curator/curator-cm.yaml
Labels: bug, not planned

#421 Increased slm cpu request slightly
  WIP-CHANGELOG.md
  helmfile/values/elasticsearch-slm.yaml.gotmpl
Labels: not planned
