Repository elastisys/compliantkubernetes-apps, pull requests merged in 2022-05, with the labels that each got.

#1007 Apps support for Elastx
  README.md
  WIP-CHANGELOG.md
  bin/common.bash
  bin/init.bash
  scripts/S3/generate-s3cfg.sh
Labels: feature

#1014 apps sc: Split dashboard configmaplist into separate configmaps
  WIP-CHANGELOG.md
  helmfile/charts/grafana-ops/templates/configmap-dashboards.yaml
Labels: bug, not planned

#1013 apps: Remove disabled releases from helmfile
  WIP-CHANGELOG.md
  helmfile/00-psp_rbac_np.yaml
  helmfile/50-applications.yaml
Labels: not planned, cleanup

#1011 apps wc: Remove undefined macro preventing falco rule compilation
  WIP-CHANGELOG.md
  helmfile/values/falco.yaml.gotmpl
Labels: bug, not planned

#1025 apps: Add missing config option for prometheus replicas
  WIP-CHANGELOG.md
  config/config/common-config.yaml
Labels: bug, not planned
