Repository elastisys/compliantkubernetes-apps, pull requests merged in 2022-01, with the labels that each got.

#752 apps sc: OpenSearch bugfixes
  WIP-CHANGELOG.md
  helmfile/values/opensearch/common.yaml.gotmpl
  migration/v0.18.x-v0.19.x/opensearch-migration-run.sh
  migration/v0.18.x-v0.19.x/upgrade-apps.md
Labels: bug

#760 tests: Fix OpenSearch client tests
  pipeline/test/services/service-cluster/testPodsReady.sh
Labels: bug, opensearch, not planned

#769 apps sc: Added node exporter full dashboard
  WIP-CHANGELOG.md
  helmfile/charts/grafana-ops/dashboards/node-exporter-full-dashboard.json
  helmfile/charts/grafana-ops/values.yaml
Labels: not planned

#774 apps sc: Pin Elasticsearch Curator version
  helmfile/charts/opensearch/curator/values.yaml
Labels: bug
