Repository elastisys/compliantkubernetes-apps, pull requests merged in 2022-11, with the labels that each got.

#1273 docs: Add migration steps for rebuilding internal OpenSearch certs
  migration/v0.25.x-v0.26.x/upgrade-apps.md
Labels: bug, opensearch

#1268 apps:enable quotes to allow rclone to be scheduled every x minutes
  WIP-CHANGELOG.md
  helmfile/charts/rclone-sync/templates/cronjob.yaml
  helmfile/values/rclone-sync.yaml.gotmpl
Labels: improvement

#1275 script: Fix cleanup script to remove PVCs instead of PVs
  WIP-CHANGELOG.md
  scripts/clean-sc.sh
  scripts/clean-wc.sh
Labels: bug, quick issue

#1279 bin: Fix update-ips script for S3/Swift ports
  bin/update-ips.bash
Labels: bug

#1281 apps: Fix flake on falco dependencies
  WIP-CHANGELOG.md
  helmfile/50-applications.yaml
  helmfile/charts/falco-psp-rbac/.helmignore
  helmfile/charts/falco-psp-rbac/Chart.yaml
  helmfile/charts/falco-psp-rbac/templates/_helpers.tpl
  helmfile/charts/falco-psp-rbac/templates/rbac.yaml
  helmfile/charts/falco-psp-rbac/values.yaml
  helmfile/charts/falco-psp/Chart.yaml
Labels: bug, pipeline

#1285 apps: Fixed instance label for node-exporter
  WIP-CHANGELOG.md
  helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
  helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl
Labels: not planned

#1312 apps: Disabled all collectors except textfile for cisbench exporter
  WIP-CHANGELOG.md
  config/config/common-config.yaml
  helmfile/charts/starboard/ciskubebench-exporter/templates/deployment.yaml
  helmfile/charts/starboard/vulnerability-exporter/templates/deployment.yaml
Labels: not planned
