Repository elastisys/compliantkubernetes-apps, pull requests merged in 2023-10, with the labels that each got.

#1809 apps: add rook-ceph-crashcollector netpols
  helmfile/charts/networkpolicy/common/templates/rook-ceph/crashcollector.yaml
  helmfile/charts/networkpolicy/common/templates/rook-ceph/mgr.yaml
  helmfile/charts/networkpolicy/common/templates/rook-ceph/mon.yaml
Labels: improvement

#1810 config: add falco tty templating
  config/config/common-config.yaml
  helmfile/values/falco/falco-common.yaml.gotmpl
Labels: falco, improvement

#1813 config: add templating for enabling wc to sc probes
  config/config/wc-config.yaml
  helmfile/values/prometheus-blackbox-exporter-wc.yaml.gotmpl
Labels: improvement

#1815 docs: update-ips command to use apply
  bin/apps.bash
  migration/template/README.md
  migration/v0.33/README.md
  migration/v0.34/README.md
Labels: documentation

#1817 apps: Allow calico-accountant drop and execute in Falco
  helmfile/values/falco/falco-common.yaml.gotmpl
Labels: falco, improvement

#1826 apps sc: Remove unused sclogs template
  helmfile/values/sc-logs-retention.yaml.gotmpl
Labels: cleanup

#1755 New test harness
  .github/pull_request_template.md
  .pre-commit-config.yaml
  tests/.dockerignore
  tests/.gitignore
  tests/Dockerfile
  tests/Makefile
  tests/README.md
  tests/common/gen-bats.bash
  tests/common/gen-cypress.bash
  tests/common/lib.bash
  tests/cypress.config.js
  tests/cypress.support.js
  tests/end-to-end/grafana-admin.cy.js
  tests/end-to-end/grafana-dashboards-discovery.bats
  tests/end-to-end/grafana-dev.cy.js
  tests/integration/template.bats
  tests/package-lock.json
  tests/package.json
  tests/regression/template.bats
  tests/unit/pods-ready.bats.yaml
Labels: feature

#1844 apps wc: Unmanaged user-alertmanager secret
  helmfile/charts/user-alertmanager/templates/secret.yaml
  migration/v0.34/README.md
  migration/v0.34/apply/70-unmanage-user-alertmanager-secret.sh
  scripts/migration/yq.sh
Labels: improvement

#1823 End-to-end tests for Harbor API
  tests/.gitignore
  tests/Makefile
  tests/README.md
  tests/common/lib.bash
  tests/common/lib/harbor.bash
  tests/end-to-end/gatekeeper-policies.bats
  tests/end-to-end/harbor-api.bats
Labels: harbor, pipeline, QA
