Repository elastisys/compliantkubernetes-apps, pull requests merged in 2023-11, with the labels that each got.

#1842 apps wc: upgrade hnc and expose opt-in propagation
  config/config/wc-config.yaml
  helmfile/00-hnc-crds.yaml
  helmfile/charts/hnc/config-and-crds/Chart.yaml
  helmfile/charts/hnc/config-and-crds/crds/hncconfigurations.yaml
  helmfile/charts/hnc/config-and-crds/templates/hnc-config.yaml
  helmfile/charts/hnc/controller/Chart.yaml
  helmfile/values/hnc/controller.yaml.gotmpl
  migration/v0.34/README.md
  migration/v0.34/apply/12-hnc-crds.sh
Labels: feature, improvement

#1861 Add more user-alertmanager config options
  config/config/wc-config.yaml
  helmfile/charts/user-alertmanager/templates/alertmanager.yaml
  helmfile/charts/user-alertmanager/values.yaml
  helmfile/values/user-alertmanager.yaml.gotmpl
Labels: improvement

#1878 apps: Add modular helmfile structure
  .pre-commit-config.yaml
  helmfile.yaml
  helmfile/bases/v2environments.yaml
  helmfile/bases/v2upstream.yaml
  helmfile/stacks/calico.yaml
  helmfile/stacks/cert-manager.yaml
  helmfile/stacks/dex.yaml
  helmfile/stacks/falco.yaml
  helmfile/stacks/fluentd.yaml
  helmfile/stacks/gatekeeper.yaml
  helmfile/stacks/harbor.yaml
  helmfile/stacks/hnc.yaml
  helmfile/stacks/ingress-nginx.yaml
  helmfile/stacks/kured.yaml
  helmfile/stacks/monitoring-grafana.yaml
  helmfile/stacks/monitoring-prometheus.yaml
  helmfile/stacks/monitoring.yaml
  helmfile/stacks/opensearch.yaml
  helmfile/stacks/rbac.yaml
  helmfile/stacks/rclone.yaml
  helmfile/stacks/system.yaml
  helmfile/stacks/thanos.yaml
  helmfile/stacks/velero.yaml
Labels: improvement, cleanup

#1885 bin: Improve validate sops config
  bin/common.bash
Labels: improvement

#1890 apps: Fixes to the new Helmfile setup
  helmfile/stacks/harbor.yaml
  helmfile/stacks/system.yaml
Labels: bug

#1888 apps: Allow DNS traffic directly to CoreDNS
  helmfile/values/networkpolicies/common/common.yaml.gotmpl
Labels: improvement

#1889 apps sc: OpenSearch Dashboards use internal communication to dex
  helmfile/charts/networkpolicy/service-cluster/templates/dex/allow-dex.yaml
  helmfile/charts/networkpolicy/service-cluster/templates/opensearch/dashboard.yaml
  helmfile/values/opensearch/dashboards.yaml.gotmpl
Labels: dex, opensearch dashboards, cleanup
