Repository elastisys/compliantkubernetes-apps, pull requests merged in 2023-02, with the labels that each got.

#1386 apps sc: Thanos configuration updates
  WIP-CHANGELOG.md
  helmfile/charts/networkpolicy-service/templates/grafana/allow-grafana.yaml
  helmfile/charts/networkpolicy-service/templates/thanos/allow-thanos-query.yaml
  helmfile/charts/networkpolicy-service/templates/thanos/allow-thanos-ruler.yaml
  helmfile/values/grafana-user.yaml.gotmpl
  helmfile/values/kube-prometheus-stack-sc.yaml.gotmpl
  helmfile/values/thanos/query.yaml.gotmpl
  helmfile/values/thanos/receiver.yaml.gotmpl
Labels: improvement, thanos

#1368 tests: Add troubleshooting script for user access & sub namespaces
  WIP-CHANGELOG.md
  bin/test.bash
  pipeline/test/services/workload-cluster/testHNC.sh
  pipeline/test/services/workload-cluster/testUserRbac.sh
Labels: QA, top-QA

#1412 apps sc: Fix OpenSearch netpol for dedicated nodes
  WIP-CHANGELOG.md
  helmfile/charts/networkpolicy-service/templates/opensearch/client.yaml
  helmfile/charts/networkpolicy-service/templates/opensearch/data.yaml
Labels: bug

#1432 apps sc: Update harbor backup job api version
  WIP-CHANGELOG.md
  helmfile/charts/harbor/harbor-backup/templates/harbor-backup-job.yaml
Labels: bug
