Repository elastisys/compliantkubernetes-apps, pull requests merged in 2023-07, with the labels that each got.

#1656 apps sc: Use emptyDir with log-manager compaction
  WIP-CHANGELOG.md
  helmfile/charts/log-manager/templates/cronjob-compaction.yaml
  helmfile/charts/log-manager/values.yaml
  helmfile/values/fluentd/log-manager.yaml.gotmpl
  helmfile/values/podsecuritypolicies/common/fluentd.yaml.gotmpl
Labels: fluentd

#1666 config: remove leftover influxdb config
  WIP-CHANGELOG.md
  config/config/common-config.yaml
  config/config/wc-config.yaml
Labels: cleanup

#1601 apps sc: Added support for swift in rclone-sync.
  WIP-CHANGELOG.md
  bin/update-ips.bash
  config/config/sc-config.yaml
  config/secrets/sc-secrets.yaml
  helmfile/charts/networkpolicy/service-cluster/templates/rclone-sync.yaml
  helmfile/charts/rclone-sync/files/rclone.conf
  helmfile/charts/rclone-sync/templates/cronjob.yaml
  helmfile/charts/rclone-sync/values.yaml
  helmfile/values/networkpolicy/service-cluster.yaml.gotmpl
  helmfile/values/rclone-sync.yaml.gotmpl
Labels: feature

#1674 apps: moved and updated our custom images
  WIP-CHANGELOG.md
  helmfile/charts/calico-accountant/values.yaml
  helmfile/charts/harbor/harbor-backup/templates/harbor-backup-job.yaml
  helmfile/charts/log-manager/Chart.yaml
  helmfile/charts/opensearch/backup/values.yaml
  helmfile/charts/opensearch/slm/values.yaml
  helmfile/charts/rclone-sync/files/rclone.conf
  helmfile/charts/rclone-sync/templates/cronjob.yaml
  helmfile/charts/rclone-sync/values.yaml
  helmfile/charts/s3-exporter/Chart.yaml
  helmfile/charts/s3-exporter/values.yaml
  images/backup-postgres/Dockerfile
  images/curl-jq/Dockerfile
  images/fluentd-elasticsearch/README.md
  images/log-manager/Dockerfile
  images/rclone-sync/Dockerfile
  scripts/restore-sync/template.job.yaml
  scripts/restore/restore-harbor-job.yaml
Labels: feature, QA

#1655 scripts: Update score script with different format
  WIP-CHANGELOG.md
  scripts/report/score.sh
  scripts/score.sh
Labels: QA

#1684 bin: preflight check to see if all keys are valid
  WIP-CHANGELOG.md
  bin/common.bash
Labels: bug

#1679 bin: upgrade prepare script fix
  WIP-CHANGELOG.md
  scripts/migration/lib.sh
Labels: bug
