Repository elastisys/compliantkubernetes-apps, pull requests merged in 2023-05, with the labels that each got.

#1533 apps wc: allow discovery of all probes
  WIP-CHANGELOG.md
  helmfile/values/kube-prometheus-stack-wc.yaml.gotmpl
Labels: bug

#1531 apps: upgrade prometheus-elasticsearch-exporter to 5.1.1
  WIP-CHANGELOG.md
  helmfile/upstream/prometheus-elasticsearch-exporter/Chart.yaml
  helmfile/upstream/prometheus-elasticsearch-exporter/README.md
  helmfile/upstream/prometheus-elasticsearch-exporter/ci/security-context.yaml
  helmfile/upstream/prometheus-elasticsearch-exporter/templates/_helpers.tpl
  helmfile/upstream/prometheus-elasticsearch-exporter/templates/deployment.yaml
  helmfile/upstream/prometheus-elasticsearch-exporter/templates/podsecuritypolicies.yaml
  helmfile/upstream/prometheus-elasticsearch-exporter/templates/servicemonitor.yaml
  helmfile/upstream/prometheus-elasticsearch-exporter/values.yaml
  helmfile/values/prometheus-opensearch-exporter.yaml.gotmpl
Labels: improvement

#1566 Linus/log manager ephemeral volumes
  WIP-CHANGELOG.md
  config/config/sc-config.yaml
  helmfile/charts/log-manager/templates/cronjob-compaction.yaml
  helmfile/values/fluentd/log-manager.yaml.gotmpl
  helmfile/values/podsecuritypolicies/common/fluentd.yaml.gotmpl
Labels: feature

#1576 apps sc: Run log-manager compact more frequently
  WIP-CHANGELOG.md
  config/config/sc-config.yaml
Labels: fluentd

#1578 apps sc: fix inconsistencies for rclone encyrption
  WIP-CHANGELOG.md
  config/config/sc-config.yaml
  config/secrets/sc-secrets.yaml
Labels: bug

#1580 apps sc: Update Falco Grafana dashboard
  WIP-CHANGELOG.md
  helmfile/charts/grafana-ops/dashboards/falco-dashboard.json
Labels: falco

#1581 apps: OPA always enabled
  WIP-CHANGELOG.md
  bootstrap/namespaces/helmfile/values/namespaces-sc.yaml.gotmpl
  bootstrap/namespaces/helmfile/values/namespaces-wc.yaml.gotmpl
  config/config/common-config.yaml
  helmfile/12-gatekeeper.yaml
  helmfile/13-gatekeeper-templates.yaml
  helmfile/50-applications.yaml
  helmfile/values/networkpolicy/common.yaml.gotmpl
  migration/v0.30/prepare/09-gatekeeper-enabled.sh
  pipeline/test/services/workload-cluster/testPodsReady.sh
Labels: gatekeeper/opa

#1555 apps sc: Added so Grafana egress can be configured from sc-config.
  WIP-CHANGELOG.md
  config/config/sc-config.yaml
  helmfile/charts/networkpolicy/service-cluster/templates/grafana/allow-grafana.yaml
  helmfile/charts/networkpolicy/service-cluster/values.yaml
  helmfile/values/networkpolicy/service-cluster.yaml.gotmpl
  pipeline/config/exoscale/sc-config.yaml
Labels: good first issue, improvement

#1603 apps sc: harbor jobservice netpol allow garbage collection
  WIP-CHANGELOG.md
  helmfile/charts/networkpolicy/service-cluster/templates/harbor/allow-harbor-jobservice.yaml
Labels: bug

#1598 apps sc: Update Trivy Operator Dashboard
  WIP-CHANGELOG.md
  helmfile/charts/grafana-ops/dashboards/trivy-operator-dashboard.json
Labels: grafana, improvement
