Repository elastisys/compliantkubernetes-apps, pull requests merged in 2023-12, with the labels that each got.

#1841 End-to-end tests for OPA Gatekeeper
  tests/common/lib.bash
  tests/common/lib/harbor.bash
  tests/end-to-end/gatekeeper-policies.bats
  tests/end-to-end/opa-gatekeeper-policies.bats
Labels: gatekeeper/opa, pipeline, QA

#1904 bin: Allow update-ips to fetch nodes without labels
  bin/update-ips.bash
Labels: bug

#1914 bin: Skip CIDR check on set-me in update-ips
  bin/update-ips.bash
  pipeline/update-ips.bats
Labels: improvement

#1913 apps: Allow ingress-nginx cluster IP to be predefined
  config/config/common-config.yaml
  helmfile/values/ingress-nginx.yaml.gotmpl
Labels: improvement, app/ingress-nginx

#1916 apps: expose extra arguments for ingress-nginx
  config/config/common-config.yaml
  helmfile/values/ingress-nginx.yaml.gotmpl
Labels: feature

#1851 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/chart-upgrade-request.yml
  .github/ISSUE_TEMPLATE/chart_upgrade.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general-issue.yml
  .github/ISSUE_TEMPLATE/investigation.md
  .github/ISSUE_TEMPLATE/investigation.yml
Labels: documentation

#1932 tests: Correct cache-image workflow
  .github/workflows/cache-image.yml
Labels: bug
