Repository elastisys/compliantkubernetes-apps, pull requests merged in 2024-07, with the labels that each got.

#2198 Fix velero psp
  helmfile.d/values/podsecuritypolicies/common/velero.yaml.gotmpl
Labels: kind/bug

#2208 config: use wildcard apache2-utils version
  REQUIREMENTS
Labels: kind/bug

#2215 Fixed netpol for fluentd-aggregator
  helmfile.d/values/networkpolicies/workload/fluentd.yaml.gotmpl
Labels: kind/bug

#2216 Upgrade opensearch and opensearch dashboards to app version v2.15.0
  helmfile.d/charts/opensearch/securityadmin/values.yaml
  helmfile.d/upstream/index.yaml
  helmfile.d/upstream/opensearch-project/opensearch-dashboards/CHANGELOG.md
  helmfile.d/upstream/opensearch-project/opensearch-dashboards/Chart.yaml
  helmfile.d/upstream/opensearch-project/opensearch-dashboards/README.md
  helmfile.d/upstream/opensearch-project/opensearch-dashboards/templates/_helpers.tpl
  helmfile.d/upstream/opensearch-project/opensearch-dashboards/templates/autoscaler.yaml
  helmfile.d/upstream/opensearch-project/opensearch-dashboards/values.yaml
  helmfile.d/upstream/opensearch-project/opensearch/CHANGELOG.md
  helmfile.d/upstream/opensearch-project/opensearch/Chart.yaml
Labels: app/opensearch, kind/improvement, app/opensearch-dashboards

#2220 apps sc: dex upgraded to app version 2.40.0 and chart version 0.18.0
  config/schemas/secrets.yaml
  config/secrets.yaml
  helmfile.d/upstream/dexidp/dex/Chart.yaml
  helmfile.d/upstream/dexidp/dex/README.md
  helmfile.d/upstream/dexidp/dex/ci/label-annotations-values.yaml
  helmfile.d/upstream/dexidp/dex/templates/deployment.yaml
  helmfile.d/upstream/dexidp/dex/templates/hpa.yaml
  helmfile.d/upstream/dexidp/dex/templates/servicemonitor.yaml
  helmfile.d/upstream/dexidp/dex/values.yaml
  helmfile.d/upstream/index.yaml
  migration/v0.40/README.md
  migration/v0.40/prepare/20-update-google-dex-config.sh
  scripts/migration/lib.sh
Labels: app/dex, kind/improvement

#2221 apps: upgrade metrics server to app v0.7.1 and chart v3.12.1
  helmfile.d/upstream/index.yaml
  helmfile.d/upstream/kubernetes-metrics-server/metrics-server/CHANGELOG.md
  helmfile.d/upstream/kubernetes-metrics-server/metrics-server/Chart.yaml
  helmfile.d/upstream/kubernetes-metrics-server/metrics-server/README.md
  helmfile.d/upstream/kubernetes-metrics-server/metrics-server/RELEASE.md
  helmfile.d/upstream/kubernetes-metrics-server/metrics-server/templates/deployment.yaml
  helmfile.d/upstream/kubernetes-metrics-server/metrics-server/values.yaml
Labels: kind/improvement

#2222 docs: remove oidc-users if restoring harbor to new domain
  scripts/restore/README.md
Labels: kind/documentation, app/harbor
