Repository elastisys/compliantkubernetes-apps, pull requests merged in 2024-05, with the labels that each got.

#2112 bin: Naive implementation for explain config or secrets
  bin/ck8s
  bin/explain.bash
Labels: kind/feature

#2067 Add external-dns with route53 support
  DEVELOPMENT.md
  README.md
  config/config/common-config.yaml
  config/secrets/sc-secrets.yaml
  helmfile.d/charts/external-dns-endpoints/.helmignore
  helmfile.d/charts/external-dns-endpoints/Chart.yaml
  helmfile.d/charts/external-dns-endpoints/templates/_helpers.tpl
  helmfile.d/charts/external-dns-endpoints/templates/dnsendpoint.yaml
  helmfile.d/charts/external-dns-endpoints/values.yaml
  helmfile.d/charts/external-dns-secrets/.helmignore
  helmfile.d/charts/external-dns-secrets/Chart.yaml
  helmfile.d/charts/external-dns-secrets/templates/_helpers.tpl
  helmfile.d/charts/external-dns-secrets/templates/external-dns-secret.yaml
  helmfile.d/charts/external-dns-secrets/values.yaml
  helmfile.d/stacks/external-dns.yaml
  helmfile.d/state.yaml
  helmfile.d/upstream/index.yaml
  helmfile.d/upstream/kubernetes-external-dns/external-dns/.helmignore
  helmfile.d/upstream/kubernetes-external-dns/external-dns/CHANGELOG.md
  helmfile.d/upstream/kubernetes-external-dns/external-dns/Chart.yaml
  helmfile.d/upstream/kubernetes-external-dns/external-dns/README.md
  helmfile.d/upstream/kubernetes-external-dns/external-dns/README.md.gotmpl
  helmfile.d/upstream/kubernetes-external-dns/external-dns/RELEASE.md
  helmfile.d/upstream/kubernetes-external-dns/external-dns/ci/ci-values.yaml
  helmfile.d/upstream/kubernetes-external-dns/external-dns/crds/dnsendpoint.yaml
  helmfile.d/upstream/kubernetes-external-dns/external-dns/templates/NOTES.txt
  helmfile.d/upstream/kubernetes-external-dns/external-dns/templates/_helpers.tpl
  helmfile.d/upstream/kubernetes-external-dns/external-dns/templates/clusterrole.yaml
  helmfile.d/upstream/kubernetes-external-dns/external-dns/templates/clusterrolebinding.yaml
  helmfile.d/upstream/kubernetes-external-dns/external-dns/templates/deployment.yaml
  helmfile.d/upstream/kubernetes-external-dns/external-dns/templates/secret.yaml
  helmfile.d/upstream/kubernetes-external-dns/external-dns/templates/service.yaml
  helmfile.d/upstream/kubernetes-external-dns/external-dns/templates/serviceaccount.yaml
  helmfile.d/upstream/kubernetes-external-dns/external-dns/templates/servicemonitor.yaml
  helmfile.d/upstream/kubernetes-external-dns/external-dns/values.schema.json
  helmfile.d/upstream/kubernetes-external-dns/external-dns/values.yaml
  helmfile.d/values/admin-namespaces-sc.yaml.gotmpl
  helmfile.d/values/admin-namespaces-wc.yaml.gotmpl
  helmfile.d/values/external-dns/external-dns.yaml.gotmpl
  helmfile.d/values/networkpolicies/common/external-dns.yaml.gotmpl
  migration/v0.38/README.md
  migration/v0.38/prepare/60-adopt-dns-records.sh
  pipeline/config/exoscale/common-config.yaml
Labels: kind/feature

#2118 scripts: Use local caches for local clusters
  DEVELOPMENT.md
  scripts/local-cluster.sh
  scripts/local-clusters/profiles/multi-node-cache.yaml
  scripts/local-clusters/profiles/single-node-cache.yaml
  scripts/local-clusters/registries/docker.io/hosts.toml
  scripts/local-clusters/registries/ghcr.io/hosts.toml
  scripts/local-clusters/registries/quay.io/hosts.toml
Labels: kind/feature

#2122 apps: Update Falco rules
  helmfile.d/values/falco/falco-common.yaml.gotmpl
Labels: app/falco, kind/improvement

#2082 tests: Add releases unit tests
  helmfile.d/stacks/ingress-nginx.yaml
  tests/common/lib/env.bash
  tests/unit/bin/init/template.bats.gotmpl
  tests/unit/bin/init/test-aws-air-gapped.gen.bats
  tests/unit/bin/init/test-aws-dev.gen.bats
  tests/unit/bin/init/test-aws-prod.gen.bats
  tests/unit/bin/init/test-baremetal-air-gapped.gen.bats
  tests/unit/bin/init/test-baremetal-dev.gen.bats
  tests/unit/bin/init/test-baremetal-prod.gen.bats
  tests/unit/bin/init/test-citycloud-air-gapped.gen.bats
  tests/unit/bin/init/test-citycloud-dev.gen.bats
  tests/unit/bin/init/test-citycloud-prod.gen.bats
  tests/unit/bin/init/test-elastx-air-gapped.gen.bats
  tests/unit/bin/init/test-elastx-dev.gen.bats
  tests/unit/bin/init/test-elastx-prod.gen.bats
  tests/unit/bin/init/test-exoscale-air-gapped.gen.bats
  tests/unit/bin/init/test-exoscale-dev.gen.bats
  tests/unit/bin/init/test-exoscale-prod.gen.bats
  tests/unit/bin/init/test-safespring-air-gapped.gen.bats
  tests/unit/bin/init/test-safespring-dev.gen.bats
  tests/unit/bin/init/test-safespring-prod.gen.bats
  tests/unit/bin/init/test-upcloud-air-gapped.gen.bats
  tests/unit/bin/init/test-upcloud-dev.gen.bats
  tests/unit/bin/init/test-upcloud-prod.gen.bats
  tests/unit/bin/update-ips/main.bats
  tests/unit/bin/update-ips/rclone.bats
  tests/unit/bin/update-ips/swift.bats
  tests/unit/releases/script.bash
  tests/unit/releases/template.bats.gotmpl
  tests/unit/releases/template.gen.bats
  tests/unit/releases/test-aws.gen.bats
  tests/unit/releases/test-baremetal.gen.bats
  tests/unit/releases/test-citycloud.gen.bats
  tests/unit/releases/test-elastx.gen.bats
  tests/unit/releases/test-exoscale.gen.bats
  tests/unit/releases/test-safespring.gen.bats
  tests/unit/releases/test-upcloud.gen.bats
Labels: kind/improvement

#2113 Disable upstream fluentd alerts
  helmfile.d/values/fluentd/forwarder-common.yaml.gotmpl
Labels: app/fluentd, app/prometheus

#2124 Add config option to allow internal traffic to Prometheus
  config/config/wc-config.yaml
  helmfile.d/values/networkpolicies/common/prometheus.yaml.gotmpl
Labels: kind/feature, app/prometheus

#2140 apps sc: fixed some typos in alerts
  helmfile.d/charts/prometheus-alerts/templates/alerts/openstack.yaml
Labels: kind/cleanup

#2144 Ignore system namespace pods with missing resource requests in cluster status dashboard
  helmfile.d/charts/grafana-dashboards/dashboards/kubernetesstatus-dashboard.json
Labels: kind/improvement

#2149 apps sc: fix rclone config
  config/config/sc-config.yaml
  config/schemas/config.yaml
  helmfile.d/values/networkpolicies/service/rclone.yaml.gotmpl
  helmfile.d/values/rclone/sync.yaml.gotmpl
Labels: kind/cleanup

#2138 Schema doc improvements and tests
  config/config/common-config.yaml
  config/config/sc-config.yaml
  config/schemas/config.yaml
  config/schemas/secrets.yaml
  helmfile.d/values/falco/falco-common.yaml.gotmpl
  tests/common/lib.bash
  tests/common/lib/env.bash
  tests/unit/schema.bats
Labels: kind/improvement
