Repository elastisys/compliantkubernetes-apps, pull requests merged in 2024-02, with the labels that each got.

#1985 tests: Regenerate resources when variable is set
  tests/README.md
  tests/unit/bin/update-ips/main.bats
Labels: improvement

#1987 Add config backup retention to init
  bin/init.bash
Labels: feature

#1986 Changed hard coded value to variable in ceph dashboard
  helmfile.d/charts/grafana-dashboards/dashboards/README.md
  helmfile.d/charts/grafana-dashboards/dashboards/cephosdsingle-dashboard.json
Labels: bug, dashboard

#1912 apps: charts to ghcr
  .github/workflows/push-to-ghcr.yml
  helmfile.d/charts/README.md
  helmfile.d/charts/public.gpg
Labels: feature

#1990 scripts: fixed harbor restore backup dir
  scripts/restore/restore-harbor.sh
Labels: bug

#1997 release: bumped kubectl version to 1.28.6
  roles/get-requirements.yaml
Labels: release

#1991 apps sc: Grafana upgrade v10.3.1
  config/config/sc-config.yaml
  helmfile.d/upstream/grafana/grafana/Chart.yaml
  helmfile.d/upstream/grafana/grafana/README.md
  helmfile.d/upstream/grafana/grafana/templates/_config.tpl
  helmfile.d/upstream/grafana/grafana/templates/_helpers.tpl
  helmfile.d/upstream/grafana/grafana/templates/_pod.tpl
  helmfile.d/upstream/grafana/grafana/templates/clusterrole.yaml
  helmfile.d/upstream/grafana/grafana/templates/clusterrolebinding.yaml
  helmfile.d/upstream/grafana/grafana/templates/configSecret.yaml
  helmfile.d/upstream/grafana/grafana/templates/configmap-dashboard-provider.yaml
  helmfile.d/upstream/grafana/grafana/templates/configmap.yaml
  helmfile.d/upstream/grafana/grafana/templates/dashboards-json-configmap.yaml
  helmfile.d/upstream/grafana/grafana/templates/deployment.yaml
  helmfile.d/upstream/grafana/grafana/templates/image-renderer-deployment.yaml
  helmfile.d/upstream/grafana/grafana/templates/ingress.yaml
  helmfile.d/upstream/grafana/grafana/templates/networkpolicy.yaml
  helmfile.d/upstream/grafana/grafana/templates/role.yaml
  helmfile.d/upstream/grafana/grafana/templates/rolebinding.yaml
  helmfile.d/upstream/grafana/grafana/templates/secret.yaml
  helmfile.d/upstream/grafana/grafana/templates/service.yaml
  helmfile.d/upstream/grafana/grafana/templates/servicemonitor.yaml
  helmfile.d/upstream/grafana/grafana/templates/tests/test.yaml
  helmfile.d/upstream/grafana/grafana/values.yaml
  helmfile.d/upstream/index.yaml
Labels: app/grafana, improvement

#2003 config: expose node-local-dns resources
  changelog/0.36.md
  config/config/common-config.yaml
  helmfile.d/charts/node-local-dns/templates/node-local-dns.yaml
  helmfile.d/values/node-local-dns.yaml.gotmpl
Labels: improvement

#2015 Add information about capacity management in docs
  README.md
Labels: documentation
