Repository elastisys/compliantkubernetes-apps, pull requests merged in 2024-04, with the labels that each got.

#2013 Add rclone restore helm chart
  config/config/sc-config.yaml
  docs/restore/rclone.md
  helmfile.d/charts/rclone/Chart.yaml
  helmfile.d/charts/rclone/templates/_.tpl
  helmfile.d/charts/rclone/templates/cronjobs.yaml
  helmfile.d/charts/rclone/templates/secret.yaml
  helmfile.d/charts/rclone/values.yaml
  helmfile.d/stacks/rclone.yaml
  helmfile.d/state.yaml
  helmfile.d/values/rclone/_.tpl
  helmfile.d/values/rclone/restore.yaml.gotmpl
  scripts/restore-sync/README.md
  scripts/restore-sync/template.job.yaml
Labels: kind/feature

#2023 Migrate rclone-sync to common chart
  helmfile.d/charts/rclone-sync/Chart.yaml
  helmfile.d/charts/rclone-sync/files/rclone.conf
  helmfile.d/charts/rclone-sync/templates/cronjob.yaml
  helmfile.d/charts/rclone-sync/templates/rclone-config.yaml
  helmfile.d/charts/rclone-sync/values.yaml
  helmfile.d/stacks/rclone.yaml
  helmfile.d/values/rclone-sync.yaml.gotmpl
  helmfile.d/values/rclone/sync.yaml.gotmpl
Labels: kind/improvement, kind/cleanup

#2057 Generate rclone network policies
  bin/update-ips.bash
  config/config/sc-config.yaml
  helmfile.d/charts/networkpolicy/service-cluster/templates/rclone/rclone-default-deny.yaml
  helmfile.d/charts/networkpolicy/service-cluster/templates/rclone/rclone-sync.yaml
  helmfile.d/charts/networkpolicy/service-cluster/values.yaml
  helmfile.d/stacks/rclone.yaml
  helmfile.d/state.yaml
  helmfile.d/values/networkpolicies/service/rclone.yaml.gotmpl
  helmfile.d/values/networkpolicy/service-cluster.yaml.gotmpl
  migration/v0.38/README.md
  migration/v0.38/apply/00-template.sh
  migration/v0.38/apply/70-service-rclone-netpol.sh
  migration/v0.38/apply/80-apply.sh
  migration/v0.38/prepare/00-template.sh
  migration/v0.38/prepare/40-service-rclone-netpol.sh
  migration/v0.38/prepare/50-init.sh
  tests/common/lib/update-ips.bash
  tests/unit/bin/update-ips/main.bats
  tests/unit/bin/update-ips/rclone.bats
  tests/unit/bin/update-ips/resources/maximal-run-full-diff.out
Labels: kind/improvement

#1943 Add tekton-pipelines controller
  config/config/sc-config.yaml
  helmfile.d/charts/tekton-pipelines/.helmignore
  helmfile.d/charts/tekton-pipelines/Chart.yaml
  helmfile.d/charts/tekton-pipelines/README.md
  helmfile.d/charts/tekton-pipelines/crds/clustertask.yaml
  helmfile.d/charts/tekton-pipelines/crds/customruns.yaml
  helmfile.d/charts/tekton-pipelines/crds/pipeline.yaml
  helmfile.d/charts/tekton-pipelines/crds/pipelineresource.yaml
  helmfile.d/charts/tekton-pipelines/crds/pipelinerun.yaml
  helmfile.d/charts/tekton-pipelines/crds/resolutionrequest.yaml
  helmfile.d/charts/tekton-pipelines/crds/run.yaml
  helmfile.d/charts/tekton-pipelines/crds/task.yaml
  helmfile.d/charts/tekton-pipelines/crds/taskrun.yaml
  helmfile.d/charts/tekton-pipelines/crds/verificationpolicies.yaml
  helmfile.d/charts/tekton-pipelines/templates/_helpers.tpl
  helmfile.d/charts/tekton-pipelines/templates/config/artifact-bucket.yaml
  helmfile.d/charts/tekton-pipelines/templates/config/artifact-pvc.yaml
  helmfile.d/charts/tekton-pipelines/templates/config/defaults.yaml
  helmfile.d/charts/tekton-pipelines/templates/config/feature-flags.yaml
  helmfile.d/charts/tekton-pipelines/templates/config/leader-election.yaml
  helmfile.d/charts/tekton-pipelines/templates/config/logging.yaml
  helmfile.d/charts/tekton-pipelines/templates/config/observability.yaml
  helmfile.d/charts/tekton-pipelines/templates/config/pipelines-info.yaml
  helmfile.d/charts/tekton-pipelines/templates/config/registry-cert.yaml
  helmfile.d/charts/tekton-pipelines/templates/config/spire.yaml
  helmfile.d/charts/tekton-pipelines/templates/config/trusted-resources.yaml
  helmfile.d/charts/tekton-pipelines/templates/controller/deployment.yaml
  helmfile.d/charts/tekton-pipelines/templates/controller/rbac.yaml
  helmfile.d/charts/tekton-pipelines/templates/controller/sa.yaml
  helmfile.d/charts/tekton-pipelines/templates/controller/service-monitor.yaml
  helmfile.d/charts/tekton-pipelines/templates/controller/service.yaml
  helmfile.d/charts/tekton-pipelines/templates/remote-resolvers/cm.yaml
  helmfile.d/charts/tekton-pipelines/templates/remote-resolvers/deployment.yaml
  helmfile.d/charts/tekton-pipelines/templates/remote-resolvers/namespace-rbac.yaml
  helmfile.d/charts/tekton-pipelines/templates/remote-resolvers/resolution-request-updates-rbac.yaml
  helmfile.d/charts/tekton-pipelines/templates/remote-resolvers/sa.yaml
  helmfile.d/charts/tekton-pipelines/templates/tekton-alerts.yaml
  helmfile.d/charts/tekton-pipelines/templates/webhook/certs.yaml
  helmfile.d/charts/tekton-pipelines/templates/webhook/cluster-access-rbac.yaml
  helmfile.d/charts/tekton-pipelines/templates/webhook/deployment.yaml
  helmfile.d/charts/tekton-pipelines/templates/webhook/mutatingwebhookconfiguration.yaml
  helmfile.d/charts/tekton-pipelines/templates/webhook/rbac.yaml
  helmfile.d/charts/tekton-pipelines/templates/webhook/sa.yaml
  helmfile.d/charts/tekton-pipelines/templates/webhook/service.yaml
  helmfile.d/charts/tekton-pipelines/templates/webhook/validatingwebhookconfiguration.yaml
  helmfile.d/charts/tekton-pipelines/values.yaml
  helmfile.d/stacks/tekton.yaml
  helmfile.d/state.yaml
  helmfile.d/values/admin-namespaces-sc.yaml.gotmpl
  helmfile.d/values/podsecuritypolicies/service/tekton-pipelines.yaml.gotmpl
  helmfile.d/values/tekton.gotmpl
Labels: kind/feature

#2074 apps: Add missing needs on admin namespaces
  helmfile.d/stacks/monitoring-prometheus.yaml
Labels: kind/bug

#2045 Port 0.35.2
  migration/v0.35/README.md
  migration/v0.35/apply/60-velero-crds-upgrade.sh
  migration/v0.35/apply/80-apply.sh
Labels: kind/release

#2103 docs: Improve rclone-restore docs
  docs/restore/rclone.md
Labels: kind/documentation
