Repository elastisys/compliantkubernetes-apps, pull requests merged in 2024-03, with the labels that each got.

#2042 Staging 0.35.2
  helmfile/values/velero-sc.yaml.gotmpl
  helmfile/values/velero-wc.yaml.gotmpl
  migration/v0.35/README.md
  migration/v0.35/apply/60-velero-crds-upgrade.sh
  migration/v0.35/apply/80-apply.sh
Labels: release

#2001 docs: Update issue templates and release resources
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/chart-upgrade-request.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/general-issue.yml
  .github/ISSUE_TEMPLATE/investigation.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/ISSUE_TEMPLATE/release.md
  .github/pull_request_template.md
  .github/workflows/end-to-end.yml
  .github/workflows/pre-commit.yml
  .github/workflows/release.yml
  .pre-commit-config.yaml
  DEVELOPMENT.md
  README.md
  changelog/0.33.md
  changelog/0.34.md
  changelog/0.35.md
  changelog/0.36.md
  helmfile.d/charts/grafana-dashboards/dashboards/thanos/thanos-receive-dashboard.json
  helmfile.d/values/kube-prometheus-stack-sc.yaml.gotmpl
  migration/template/README.md
  migration/v0.25.x-v0.26.x/upgrade-apps.md
  migration/v0.26.x-v0.27.x/upgrade-apps.md
  migration/v0.29/README.md
  migration/v0.30/README.md
  migration/v0.31/README.md
  migration/v0.32/README.md
  migration/v0.33/README.md
  migration/v0.34/README.md
  migration/v0.35/README.md
  migration/v0.36/README.md
  pipeline/test/services/test-sc.sh
  release/README.md
  release/generate-release-notes.sh
  release/stage-release.sh
Labels: documentation, QA

#2039 Upgrade cert-manager to v1.12.8
  config/config/common-config.yaml
  helmfile.d/charts/issuers/templates/letsencrypt-prod.yaml
  helmfile.d/charts/issuers/templates/letsencrypt-staging.yaml
  helmfile.d/upstream/index.yaml
  helmfile.d/upstream/jetstack/cert-manager/Chart.yaml
  helmfile.d/upstream/jetstack/cert-manager/README.md
  helmfile.d/upstream/jetstack/cert-manager/templates/cainjector-deployment.yaml
  helmfile.d/upstream/jetstack/cert-manager/templates/cainjector-poddisruptionbudget.yaml
  helmfile.d/upstream/jetstack/cert-manager/templates/cainjector-rbac.yaml
  helmfile.d/upstream/jetstack/cert-manager/templates/crds.yaml
  helmfile.d/upstream/jetstack/cert-manager/templates/deployment.yaml
  helmfile.d/upstream/jetstack/cert-manager/templates/poddisruptionbudget.yaml
  helmfile.d/upstream/jetstack/cert-manager/templates/rbac.yaml
  helmfile.d/upstream/jetstack/cert-manager/templates/startupapicheck-job.yaml
  helmfile.d/upstream/jetstack/cert-manager/templates/webhook-deployment.yaml
  helmfile.d/upstream/jetstack/cert-manager/templates/webhook-poddisruptionbudget.yaml
  helmfile.d/upstream/jetstack/cert-manager/templates/webhook-psp-clusterrole.yaml
  helmfile.d/upstream/jetstack/cert-manager/values.yaml
  helmfile.d/values/cert-manager.yaml.gotmpl
  migration/v0.37/README.md
  migration/v0.37/apply/00-template.sh
  migration/v0.37/apply/80-apply.sh
  migration/v0.37/prepare/00-template.sh
  migration/v0.37/prepare/50-init.sh
  migration/v0.37/prepare/60-move-issuer-ingress-class.sh
Labels: kind/improvement, app/cert-manager

#2050 apps: Template allocate load balancer node ports conditionally
  helmfile.d/values/ingress-nginx.yaml.gotmpl
Labels: kind/bug, app/ingress-nginx

#2012 bin: Update dependencies
  migration/v0.37/README.md
  pipeline/Dockerfile
  roles/get-requirements.yaml
  tests/Dockerfile
Labels: kind/improvement
