Repository elastisys/compliantkubernetes-apps, pull requests merged in 2025-01, with the labels that each got.

#2368 apps sc: add sub path and name suffix to rclone jobs, harbor restore support azure
  config/sc-config.yaml
  config/schemas/config.yaml
  helmfile.d/charts/rclone/templates/cronjobs.yaml
  helmfile.d/charts/rclone/values.yaml
  helmfile.d/values/rclone/restore.yaml.gotmpl
  helmfile.d/values/rclone/sync.yaml.gotmpl
  migration/v0.43/README.md
  restore/harbor/README.md
  restore/harbor/harbor-rclone-azure.yaml
Labels: app/harbor, kind/improvement

#2203 apps sc: Alert size over limit only on active indicies
  helmfile.d/charts/prometheus-alerts/templates/alerts/opensearch.yaml
Labels: kind/improvement

#2393 Fix config schema
  config/schemas/config.yaml
Labels: kind/bug

#2398 tests: Workflow improvements
  .github/workflows/tests.yml
Labels: kind/improvement

#2410 docs: small documentation fixes
  config/schemas/secrets.yaml
  helmfile.d/charts/prometheus-alerts/templates/alerts/kubernetes-apps.yaml
  migration/template/README.md
Labels: kind/documentation

#2397 apps sc: upgrade kured to 1.16.2 and switch reboot method to signal
  helmfile.d/upstream/index.yaml
  helmfile.d/upstream/kubereboot/kured/Chart.yaml
  helmfile.d/upstream/kubereboot/kured/README.md
  helmfile.d/values/kured.yaml.gotmpl
  helmfile.d/values/podsecuritypolicies/common/kured.yaml.gotmpl
Labels: kind/improvement, app/kured

#2400 Aarnq/tests jsonschema2md
  scripts/run-from-container.sh
  tests/Dockerfile
  tests/unit/general/schema.bats
Labels: kind/improvement

#2420 scripts: update sops version to v3.9.4
  REQUIREMENTS
  pipeline/Dockerfile
  tests/Dockerfile
Labels: kind/improvement
