Repository elastisys/compliantkubernetes-apps, pull requests merged in 2025-08, with the labels that each got.

#2627 Add E2E tests for packets handled by network policies
  tests/end-to-end/netpol/netpol.cy.js
  tests/end-to-end/netpol/netpol.gen.bats
Labels: kind/feature, QA

#2647 Reliable socat popups for localhost:8000 during end-to-end-test runs
  .gitignore
  REQUIREMENTS
  roles/get-requirements.yaml
  scripts/run-from-container.sh
  tests/Dockerfile
  tests/Makefile
  tests/bats.lib.bash
  tests/common/cypress/support.js
  tests/common/exec.bash
  tests/end-to-end/.bin/x-www-browser
  tests/end-to-end/general/bin-diagnostics.bats
  tests/end-to-end/grafana/dashboards-discovery.bats
  tests/end-to-end/hnc/test-hnc.bats
  tests/end-to-end/kubernetes/bin-access.bats
  tests/end-to-end/opa-gatekeeper/policies.bats
  tests/package-lock.json
  tests/package.json
Labels: QA

#2657 Add eslint for JS tests
  .pre-commit-config.yaml
  tests/common/check-js.bash
  tests/common/cypress/grafana.js
  tests/common/cypress/harbor.js
  tests/common/cypress/index.d.ts
  tests/common/cypress/support.js
  tests/cypress.config.js
  tests/cypress/fixtures/falco-event-generator-actions.json
  tests/end-to-end/alertmanager/expected-alerts.cy.js
  tests/end-to-end/falco/alerts.cy.js
  tests/end-to-end/falco/logs.cy.js
  tests/end-to-end/falco/setup_suite.bash
  tests/end-to-end/grafana/admin-promotion-ops.cy.js
  tests/end-to-end/grafana/datasources.cy.js
  tests/end-to-end/harbor/use-ui.cy.js
  tests/end-to-end/netpol/netpol.cy.js
  tests/end-to-end/opensearch/dashboards.cy.js
  tests/eslint.config.js
  tests/integration/harbor/use-ui.cy.js
  tests/package-lock.json
  tests/package.json
  tests/tsconfig.json
Labels: QA

#2688 docs: Add note on using same config with new names
  restore/rclone/README.md
Labels: kind/documentation

#2692 Improve Log Manager E2E suite
  tests/bats.lib.bash
  tests/end-to-end/log-manager/compaction-audit-sc.gen.bats
  tests/end-to-end/log-manager/compaction-audit-wc.gen.bats
  tests/end-to-end/log-manager/compaction-sc-logs.gen.bats
  tests/end-to-end/log-manager/compaction.bats.gotmpl
  tests/end-to-end/log-manager/resources/calico-allow-all.yaml
  tests/end-to-end/log-manager/retention-audit-sc.gen.bats
  tests/end-to-end/log-manager/retention-audit-wc.gen.bats
  tests/end-to-end/log-manager/retention-sc-logs.gen.bats
  tests/end-to-end/log-manager/retention.bats.gotmpl
  tests/end-to-end/log-manager/setup_suite.bash
Labels: QA

#2695 Improve Alertmanager E2E suite
  tests/end-to-end/alertmanager/expected-alerts.cy.js
Labels: QA

#2691 Improve Grafana E2E test suite
  helmfile.d/charts/grafana-dashboards/dashboards/nginx-dashboard.json
  tests/common/cypress/grafana.js
  tests/common/cypress/support.js
  tests/end-to-end/grafana/admin-promotion-ops.cy.js
  tests/end-to-end/grafana/admin-promotion-ops.gen.bats
  tests/end-to-end/grafana/admin-promotion-user.cy.js
  tests/end-to-end/grafana/admin-promotion-user.gen.bats
  tests/end-to-end/grafana/dashboards-admin.cy.js
  tests/end-to-end/grafana/dashboards-dev.cy.js
  tests/end-to-end/grafana/datasources.cy.js
  tests/end-to-end/harbor/use-ui.cy.js
  tests/end-to-end/opensearch/dashboards.cy.js
  tests/integration/harbor/use-ui.cy.js
Labels: QA

#2693 Retry on network failure during access tests
  tests/end-to-end/kubernetes/authentication-admin.cy.js
  tests/end-to-end/kubernetes/authentication-dev.cy.js
Labels: QA
