Repository elastisys/compliantkubernetes-apps, pull requests merged in 2025-04, with the labels that each got.

#2489 requirements: Move to Noble and update all requirements
  REQUIREMENTS
  tests/Dockerfile
Labels: test/integration

#2492 apps: hnc mirror image
  helmfile.d/charts/hnc/controller/values.yaml
  helmfile.d/values/falco/falco-common.yaml.gotmpl
Labels: kind/improvement

#2490 Prepare for Helmfile v1 / Introduce default disabled environment
  helmfile.d/bases/environments.yaml.gotmpl
  helmfile.d/charts/calico-felix-metrics/templates/service.yaml
  helmfile.d/stacks/calico.yaml.gotmpl
  helmfile.d/stacks/cert-manager.yaml.gotmpl
  helmfile.d/stacks/dex.yaml.gotmpl
  helmfile.d/stacks/external-dns.yaml.gotmpl
  helmfile.d/stacks/falco.yaml.gotmpl
  helmfile.d/stacks/fluentd.yaml.gotmpl
  helmfile.d/stacks/gatekeeper.yaml.gotmpl
  helmfile.d/stacks/gpu-operator.yaml.gotmpl
  helmfile.d/stacks/harbor.yaml.gotmpl
  helmfile.d/stacks/hnc.yaml.gotmpl
  helmfile.d/stacks/ingress-nginx.yaml.gotmpl
  helmfile.d/stacks/kured.yaml.gotmpl
  helmfile.d/stacks/kyverno.yaml.gotmpl
  helmfile.d/stacks/local.yaml.gotmpl
  helmfile.d/stacks/monitoring-grafana.yaml.gotmpl
  helmfile.d/stacks/monitoring-prometheus.yaml.gotmpl
  helmfile.d/stacks/monitoring.yaml.gotmpl
  helmfile.d/stacks/namespaces.yaml.gotmpl
  helmfile.d/stacks/opensearch.yaml.gotmpl
  helmfile.d/stacks/rbac.yaml.gotmpl
  helmfile.d/stacks/rclone.yaml.gotmpl
  helmfile.d/stacks/system.yaml.gotmpl
  helmfile.d/stacks/tekton.yaml.gotmpl
  helmfile.d/stacks/thanos.yaml.gotmpl
  helmfile.d/stacks/velero.yaml.gotmpl
  helmfile.d/state.yaml.gotmpl
  migration/v0.46/apply/50-remove-calico-felix-metrics-cluster-api.sh
Labels: kind/improvement

#2503 tests: Update for sc and wc local clusters
  scripts/local-cluster.sh
  tests/bats.lib.bash
  tests/common/bats/local-cluster.bash
  tests/common/exec.bash
  tests/integration/general/local-clusters.bats
  tests/integration/harbor/setup_suite.bash
Labels: kind/improvement

#2494 Update local cluster setup & documentation
  DEVELOPMENT.md
  bin/ck8s
  bin/common.bash
  config/schemas/config.yaml
  helmfile.d/bases/environments.yaml.gotmpl
  scripts/local-cluster.sh
  scripts/local-clusters/configs/common-config.yaml
  scripts/local-clusters/configs/partial/sc-node-local-dns.yaml
  scripts/local-clusters/configs/partial/wc-node-local-dns.yaml
  scripts/local-clusters/profiles/multi-node-cache.yaml
  scripts/local-clusters/profiles/multi-node.yaml
  scripts/local-clusters/profiles/single-node-cache.yaml
  scripts/local-clusters/profiles/single-node.yaml
  scripts/local-clusters/resolves/Corefile
  tests/bats.lib.bash
  tests/common/bats/local-cluster.bash
  tests/common/exec.bash
  tests/integration/general/local-clusters.bats
  tests/integration/harbor/setup_suite.bash
Labels: kind/documentation, kind/improvement, not planned

#2507 Purge yq3
  README.md
  REQUIREMENTS
  bin/common.bash
  bin/diagnostics.bash
  bin/dry-run.bash
  bin/explain.bash
  bin/fix-psp-violations.bash
  bin/init.bash
  bin/kubeconfig.bash
  bin/team.bash
  bin/update-ips.bash
  config/schemas/README.md
  config/schemas/config.yaml
  docs/sbom.yaml
  helmfile.d/charts/gatekeeper/templates/files/update.sh
  helmfile.d/charts/harbor/harbor-backup/scripts/harbor-backup.sh
  pipeline/Dockerfile
  pipeline/README.md
  pipeline/common.bash
  pipeline/test/services/service-cluster/testCertManager.sh
  pipeline/test/services/service-cluster/testEndpoints.sh
  pipeline/test/services/service-cluster/testIngress.sh
  pipeline/test/services/service-cluster/testOpensearch.sh
  pipeline/test/services/service-cluster/testPodsReady.sh
  pipeline/test/services/service-cluster/testPrometheusTargets.sh
  pipeline/test/services/workload-cluster/testCertManager.sh
  pipeline/test/services/workload-cluster/testEndpoints.sh
  pipeline/test/services/workload-cluster/testHNC.sh
  pipeline/test/services/workload-cluster/testIngress.sh
  pipeline/test/services/workload-cluster/testPodsReady.sh
  pipeline/test/services/workload-cluster/testUserRbac.sh
  release/qa-checklist.md
  restore/harbor/README.md
  roles/get-requirements.yaml
  scripts/S3/entry.sh
  scripts/azure/storage-manager.sh
  scripts/charts.sh
  scripts/clean-sc.sh
  scripts/clean-wc.sh
  scripts/local-cluster.sh
  scripts/migration/helm.sh
  scripts/migration/helmfile.sh
  scripts/migration/lib.sh
  scripts/migration/yq.sh
  scripts/report/score.sh
  scripts/run-from-container.sh
  tests/Dockerfile
  tests/common/bats/update-ips.bash
  tests/common/bats/yq.bash
  tests/cypress.support.js
  tests/end-to-end/general/bin-diagnostics.bats
  tests/end-to-end/grafana/dashboards-discovery.bats
  tests/end-to-end/velero/common.bash
  tests/integration/general/local-clusters.bats
  tests/unit/general/bin-update-ips-rclone.bats
  tests/unit/general/schema.bats
Labels: kind/improvement, kind/cleanup

#2510 apps wc: expose internal ingress-nginx LB config
  config/common-config.yaml
  config/providers/aws/wc-config.yaml
  config/providers/azure/wc-config.yaml
  config/providers/elastx/wc-config.yaml
  config/providers/openstack/wc-config.yaml
  config/schemas/config.yaml
  config/wc-config.yaml
  helmfile.d/values/ingress-nginx.yaml.gotmpl
Labels: kind/feature
