Repository elastisys/compliantkubernetes-apps, pull requests merged in 2025-05, with the labels that each got.

#2520 bin: Correct state path
  .github/CODEOWNERS
  .pre-commit-config.yaml
  bin/apply.bash
  helmfile.d/README.md
Labels: kind/bug

#2522 config: Flatten ingress-nginx schema
  config/common-config.yaml
  config/schemas/config.yaml
  config/wc-config.yaml
  helmfile.d/values/ingress-nginx.yaml.gotmpl
  tests/unit/general/bin-conditional-set-me.bats
Labels: kind/bug

#2525 Bats love 🦇
  tests/Dockerfile
  tests/common/bats/gpg.bash
Labels: kind/improvement

#2527 scripts: Add option to enable self-signed from start
  scripts/local-cluster.sh
  scripts/local-clusters/configs/partial/common-self-signed.yaml
Labels: kind/improvement

#2521 Centralized container image configuration
  bin/common.bash
  config/common-config.yaml
  config/schemas/config.yaml
  helmfile.d/README.md
  helmfile.d/bases/environments.yaml.gotmpl
  helmfile.d/lists/images.yaml
  helmfile.d/values/_helpers.tpl
  helmfile.d/values/ingress-nginx.yaml.gotmpl
  scripts/migration/lib.sh
  tests/unit/general/images.bats
  tests/unit/general/resources/images-parametric-tests.json
Labels: app/ingress-nginx

#2537 fix: later declaration of "operator" map overwrites all values in first
  helmfile.d/values/gpu-operator.yaml.gotmpl
Labels: kind/bug, not planned

#2540 tests: Optimisations
  bin/common.bash
  tests/bats.lib.bash
  tests/unit/templates/releases.bash
Labels: kind/improvement

#2542 apps sc: make disk performance alerts less sensitive
  config/sc-config.yaml
  config/schemas/config.yaml
Labels: kind/improvement
