Repository elastisys/compliantkubernetes-apps, pull requests merged in 2025-09, with the labels that each got.

#2713 fix: global network policy compatibility with kubespray
  tests/end-to-end/log-manager/resources/calico-allow-all.yaml
Labels: kind/bug

#2712 fix: prevent cronjob name from ending in '-'
  tests/bats.lib.bash
Labels: kind/bug

#2701 Apps install script for QA
  scripts/qa/README.md
  scripts/qa/boilerplate.py
  scripts/qa/config.json.sample
  scripts/qa/config.py
  scripts/qa/install_apps.py
  tests/common/exec.bash
Labels: epic, QA

#2721 falco: switch over to the 'modern_ebpf' driver by default
  config/common-config.yaml
  config/schemas/config.yaml
  helmfile.d/values/falco/falco-common.yaml.gotmpl
  migration/v0.49/prepare/10-update-falco-driver.sh
  tests/unit/general/images.bats
Labels: app/falco

#2751 tests: Add upstream chart drift tests
  scripts/run-from-container.sh
  tests/unit/general/chart-drift.bats
Labels: kind/improvement, QA
