Repository elastisys/compliantkubernetes-apps, pull requests merged in 2025-07, with the labels that each got.

#2580 apps: alertmanager migration write to tmp
  migration/v0.47/apply/30-alertmanager.sh
Labels: kind/bug

#2587 cilium: include internal cilium IPs in the update-ips flow
  bin/update-ips.bash
  tests/common/bats/update-ips.bash
  tests/unit/general/bin-update-ips-rclone.bats
  tests/unit/general/bin-update-ips-subnet.bats
  tests/unit/general/bin-update-ips.bats
Labels: kind/improvement

#2612 feat: tell cypress to run in "headed" mode
  scripts/run-from-container.sh
  tests/README.md
  tests/bats.lib.bash
Labels: not planned, QA
